import Hero from '../src/containers/CustomHero';
import Head from 'next/head';
import CustomNavBar from '../src/containers/CustomNavBar';
import LogoSection from '../src/containers/LogoSection';
import styles from '../styles/Home.module.css';
import CaptionCarousel from '../src/views/Carousel';
import { Box, Heading, Stack, Text } from '@chakra-ui/react';
import { useGetSponsorImagesQuery } from '../src/redux/sponsors/slice';
import { memo, useMemo } from 'react';
import { ILogoData } from '../src/types';

export default memo(function Home() {
  const { data, error } = useGetSponsorImagesQuery(null)

  const logosData: ILogoData[] | undefined  = useMemo(()=> data?.data , [data?.data])

  return (
    <div className={styles.container}>
      <Head>
        <title>Observatorio</title>
        <link
        rel="stylesheet"
        type="text/css"
        charSet="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomNavBar />
      <Hero />
      <CaptionCarousel cards={
       logosData?.map(({url_image}, index) => (
        <Box
          key={index}
          height={{base:'50vh', md:'1xl'}}
          backgroundSize='50%'
          position="relative"
          backgroundPosition="center"
          backgroundRepeat="no-repeat"
          backgroundImage={`url(${url_image})`}>
        </Box>
      ))
      }/>
      <LogoSection data={logosData}/>
    </div>
  );
})
